In [1]:
#coding=utf-8
import numpy as np
import pandas as pd

In [7]:
df = pd.read_csv("../1.csv", names=['one_node_longitude', 'one_node_latitude', 'kongbai', 'two_node_longitude', 'two_node_latitude'])
# print (df)
# print (df['one_node_longitu de'])
# dataframe to matrix
df_matrix= df.as_matrix()
# float64 to float32
df_matrix_f32 = np.float32(df_matrix)
print (df_matrix_f32, df_matrix_f32.shape, df_matrix_f32.shape[0], df_matrix_f32.shape[1],df_matrix_f32.dtype,)

[[ 0.69131273  0.62795222         nan  0.86645776  0.64781886]
 [ 0.69271284  0.62114477         nan  0.86632442  0.64795774]
 [ 0.69597971  0.61461514         nan  0.86632442  0.64809668]
 ..., 
 [ 0.80212015  0.80188942         nan  0.89392626  0.59572101]
 [ 0.80205345  0.80202836         nan  0.89379293  0.59585994]
 [ 0.80192012  0.8021673          nan  0.89365959  0.59613782]] (149600, 5) 149600 5 float32


In [99]:
# 切片
def get_train_data(scale = 0.8):
    x_train_input1 = df_matrix_f32[0:95744, 0:2]
    a1 = np.ones(95744)[np.newaxis]
    b1 = np.zeros(95744)[np.newaxis]
    c1 = np.vstack((a1, b1))
    x_train_label1 = c1.T
    x_train_input2 = df_matrix_f32[0:95744:, 3:]
    a2 = np.ones(95744)[np.newaxis]
    b2 = np.zeros(95744)[np.newaxis]
    c2 = np.vstack((b2, a2))
    x_train_label2 = c2.T
    x_train_input = np.vstack((x_train_input1, x_train_input2))
    x_train_label = np.vstack((x_train_label1, x_train_label2))
    return x_train_input.shape, x_train_label
print (get_train_data())

((191488, 2), array([[ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       ..., 
       [ 0.,  1.],
       [ 0.,  1.],
       [ 0.,  1.]]))


In [10]:
def get_test_data(scale = 0.8):
    index = (df_matrix_f32.shape[0])*scale
    index = np.int(index)
    cut_index = index * (1 - scale)
    x_test_input1 = df_matrix_f32[95744:, 0:2]
#     print (x_train_input1.shape)
    a1 = np.ones(53856)[np.newaxis]
    b1 = np.zeros(53856)[np.newaxis]
    c1 = np.vstack((a1, b1))
    x_test_label1 = c1.T
    x_test_input2 = df_matrix_f32[95744:, 3:]
    a2 = np.ones(53856)[np.newaxis]
    b2 = np.zeros(53856)[np.newaxis]
    c2 = np.vstack((b2, a2))
    x_test_label2 = c2.T
    x_test_input = np.vstack((x_test_input1, x_test_input2))
    x_test_label = np.vstack((x_test_label1, x_test_label2))
    print (x_test_input.shape, x_test_label.shape)
    return x_test_input, x_test_label
print (get_test_data())

(107712, 2) (107712, 2)
(array([[ 0.76985133,  0.70172268],
       [ 0.76985133,  0.70172268],
       [ 0.76985133,  0.70186162],
       ..., 
       [ 0.89392626,  0.59572101],
       [ 0.89379293,  0.59585994],
       [ 0.89365959,  0.59613782]], dtype=float32), array([[ 1.,  0.],
       [ 1.,  0.],
       [ 1.,  0.],
       ..., 
       [ 0.,  1.],
       [ 0.,  1.],
       [ 0.,  1.]]))


In [94]:
tensor1 = np.zeros(7)
tensor2 = np.ones(3)
print(tensor1.shape)
tensor = np.hstack((tensor1, tensor2))
print(tensor, tensor.shape)

(7,)
[ 0.  0.  0.  0.  0.  0.  0.  1.  1.  1.] (10,)


In [92]:
tensor = tensor[np.newaxis]
a = 0
print (tensor, len(tensor[0]))
for i in range(len(tensor[0])):
    print(tensor[0][i])
    if tensor[0][i] == 1:     
        a = a + 1
print(a/len(tensor[0]))

[[ 0.  0.  0.  0.  0.  0.  0.  1.  1.  1.]] 10
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
1.0
1.0
0.3


In [96]:
    tensor = np.ones((1,10))
    a = 0
    print (tensor, tensor.shape)
    for i in range(tensor.shape[0]):
        print(tensor[0][i])
        if tensor[0][i] == 1:
            a = a + 1
 


[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]] (1, 10)
1.0


In [98]:
def accurances(tensor = np.ones((1,10))):
    a = 0
    print (tensor, tensor.shape)
    for i in range(tensor.shape[0]):
        print(tensor[0][i])
        if tensor[0][i] == 1:
            a = a + 1
    return a / len(tensor[0])
print(accurances())

[[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]] (1, 10)
1.0
0.1
